RecordTimer.py: Fix crash on boot when recording
Got the following exception when a recording was set to start while
the box was booting up:
AttributeError: 'NoneType' object has no attribute 'execing'

Apparently, Screens.InfoBar.InfoBar.instance wasn't set yet, so check
on that first. Also use multiple lines for display.

iServiceRecord.prepare: Last two arguments must be bool, not integer.

From Commit [68bfe7] Authored by: Mike Looijmans 2014-08-22