Hotkey: Small changes required for previous commit
To avoid an ImportError: cannot import name SimpleChannelSelection

Sorry I forgot to commit these changes in Hotkey.py with my previous
commit. Thanks IMS for reporting!

From Commit [8b0473] Authored by: littlesat 2014-11-30